[concert_upcoming]
title = "아티스츠카드 ─ 온라인 콘서트 ─ 예정 콘서트"
url = "https://artistscard.com/concert/upcoming"
entrySelector = "div.sc-1xh382h-0.gnGyVZ div.sc-1jvru78-0.fJjTvE"
titleSelector = "span.sc-ozzs8q-0.hBjCtM.sc-h3kawc-3.bNIsWh"
linkSelector = "*"
contentSelector = "span.sc-ozzs8q-0.eKmNiL.sc-h3kawc-4.fknMvX"
imageSelector = "img.sc-h3kawc-0.kXWOgK"
waitUntil = "networkidle"

[concert_last]
title = "아티스츠카드 ─ 온라인 콘서트 ─ 지난 콘서트"
url = "https://artistscard.com/concert/last"
entrySelector = "div.sc-1xh382h-0.gnGyVZ div.sc-1jvru78-0.fJjTvE"
titleSelector = "span.sc-ozzs8q-0.hBjCtM.sc-h3kawc-3.bNIsWh"
linkSelector = "*"
contentSelector = "span.sc-ozzs8q-0.eKmNiL.sc-h3kawc-4.fknMvX"
imageSelector = "img.sc-h3kawc-0.kXWOgK"
waitUntil = "networkidle"
