[artistscard]
title = "Artists'Card"
url = "https://artistscard.com/ko/ticket"
entrySelector = "div[class='sc-1cyq3hq-3 jzKJLm'] div[class='sc-1e3tjec-0 gbEYpG']"
titleSelector = "div[class='sc-1e3tjec-5 sc-1e3tjec-7 bcogIH jxILRF']"
linkSelector = "*"
contentSelector = "div[class='sc-1e3tjec-5 sc-1e3tjec-8 bcogIH fEyMUm']"
waitUntil = "networkidle"
onFail = "stale"